logging:
  level:
    uk.jsikora: debug
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://192.168.0.6:5432/woodworks
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 8000
      org:
        hibernate:
          envers:
            track_entities_changed_in_revision: true
    show-sql: false

  session:
    jdbc:
      initialize-schema: always
#    store-type: jdbc
  banner:
    location: banner/banner.txt
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_schema_history

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: Ov23liZsTURzJNQnilDz
            client-secret: ${OA_DEV_GOOGLE_SECRET}
            scope:
              - openid
              - profile
              - email
          github:
            client-id: Ov23liZsTURzJNQnilDz
            client-secret: ${OA_DEV_GITHUB_SECRET}
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
#            client-authentication-method: post
#            provider: github
#        provider:
#          github:
#            authorization-uri: https://github.com/login/oauth/authorize
#            token-uri: https://github.com/login/oauth/access_token
#            user-info-uri: https://api.github.com/user
#            user-name-attribute: login