logging:
  level:
    uk.jsikora: debug
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://192.168.0.6:5432/woodworks
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 8000
      org:
        hibernate:
          envers:
            track_entities_changed_in_revision: true
    show-sql: false

  session:
    jdbc:
      initialize-schema: always
  banner:
    location: banner/banner.txt
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_schema_history

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1060834102689-amgsfr2qu0adpkp1bl7jlbdl6v9os7nn.apps.googleusercontent.com
            client-secret: ${OA_DEV_GOOGLE_SECRET}
            scope: openid, profile, email
          github:
            client-id: Ov23liZsTURzJNQnilDz
            client-secret: ${OA_DEV_GITHUB_SECRET}
            scope: read:user