CREATE TABLE base_user
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID,
    email       VARCHAR(255),
    name        VARCHAR(255),
    image_url   VARCHAR(255),
    provider    VARCHAR(255),
    provider_id VARCHAR(255),
    login       VARCHAR(255),
    locale      VARCHAR(255),
    CONSTRAINT pk_baseuser PRIMARY KEY (id)
);