CREATE TABLE base_user
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255),
    name        VARCHAR(255),
    image_url   VARCHAR(255),
    provider    VARCHAR(255),
    provider_id VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);