CREATE TABLE kitchen_draft
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid          UUID                                    NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    cabinets_json TEXT                                    NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_kitchen_draft PRIMARY KEY (id),
    CONSTRAINT fk_kitchen_draft_user FOREIGN KEY (user_id) REFERENCES base_user (id) ON DELETE CASCADE
);

CREATE INDEX idx_kitchen_draft_user_id ON kitchen_draft (user_id);
CREATE INDEX idx_kitchen_draft_uuid ON kitchen_draft (uuid);
CREATE INDEX idx_kitchen_draft_updated_at ON kitchen_draft (updated_at DESC);
