name: Deploy Woodworks STAG

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    # runs-on: wsl

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t chodzi/woodworks-api:latest .
          docker push chodzi/woodworks-api:latest

      - name: SSH into Server and Pull
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_SSH_USER }}
          password: ${{ secrets.SERVER_SSH_PASS }}
          script: |
            docker pull chodzi/woodworks-api:latest

      - name: SSH into Server and Stop
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_SSH_USER }}
          password: ${{ secrets.SERVER_SSH_PASS }}
          script: |
            docker stop woodworks-api || true
            docker rm woodworks-api || true

      - name: SSH into Server and RM
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_SSH_USER }}
          password: ${{ secrets.SERVER_SSH_PASS }}
          script: |
            docker rm woodworks-api || true

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_SSH_USER }}
          password: ${{ secrets.SERVER_SSH_PASS }}
          script: |
            docker run -d --restart unless-stopped --name woodworks-api-prod -p 9666:9666 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e DB_USER_PROD=${{ secrets.DB_USER_PROD }} \
              -e DB_PASS_PROD=${{ secrets.DB_PASS_PROD }} \
              -e OA_PROD_GITHUB_SECRET=${{ secrets.OA_PROD_GITHUB_SECRET }} \
              -e OA_PROD_GOOGLE_SECRET=${{ secrets.OA_PROD_GOOGLE_SECRET }} \
              chodzi/woodworks-api:latest
